### ISSUE TITLE
The perf plugin isn't seen as a source

### ISSUE THREAD

**Issue by titouanj** [alumet-dev/alumet#11]
It seems that the perf plugin cannot be used as the only source for the moment...

## Expected Behavior

The plugin perf should be able to run alone as a source. I've compiled alumet with the following plugins: [CsvPlugin, SocketControlPlugin, PerfPlugin], but the agent cannot start correctly to monitor a single process launched with `exec`.

## Current Behavior

```bash
./rust/alumet/target/debug/alumet-agent exec sleep 1
[2024-06-12T14:43:47Z INFO  alumet_agent] Starting ALUMET agent v0.4.1
[2024-06-12T14:43:47Z INFO  alumet::agent] Initializing the plugins...
[2024-06-12T14:43:47Z INFO  alumet::agent] 3 plugins initialized.
[2024-06-12T14:43:47Z INFO  alumet::agent] Starting the plugins...
[2024-06-12T14:43:47Z INFO  alumet::agent] Plugin startup complete.
    🧩 3 plugins started:
        - csv v0.2.0
        - socket-control v0.1.0
        - perf v0.1.0
    📏 4 metrics registered:
        - perf_hardware_REF_CPU_CYCLES: U64 ()
        - perf_hardware_CACHE_MISSES: U64 ()
        - perf_hardware_BRANCH_MISSES: U64 ()
        - perf_cache_LL_READ_MISS: U64 ()
    📥 0 source, 🔀 0 transform and 📝 1 output registered.
[2024-06-12T14:43:47Z INFO  alumet::agent] Building the measurement pipeline...
[2024-06-12T14:43:47Z ERROR alumet_agent] Pipeline failed to build

    Caused by:
        invalid pipeline configuration: no Source
thread 'main' panicked at app-agent/src/main.rs:61:9:
ALUMET agent failed to start: Pipeline failed to build
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here are the backtraces:

- <details>
  <summary>RUST_BACKTRACE=1</summary>

  ```log
    Stack backtrace:
       0: <E as anyhow::context::ext::StdError>::ext_context
                 at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.82/src/context.rs:27:29
       1: anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context
                 at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.82/src/context.rs:54:31
       2: alumet::agent::Agent::start
                 at ./rust/alumet/alumet/src/agent.rs:223:24
       3: alumet_agent::main
                 at ./rust/alumet/app-agent/src/main.rs:56:29
       4: core::ops::function::FnOnce::call_once
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
       5: std::sys_common::backtrace::__rust_begin_short_backtrace
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:155:18
       6: std::rt::lang_start::{{closure}}
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/rt.rs:166:18
       7: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:284:13
       8: std::panicking::try::do_call
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:554:40
       9: std::panicking::try
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:518:19
      10: std::panic::catch_unwind
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panic.rs:142:14
      11: std::rt::lang_start_internal::{{closure}}
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/rt.rs:148:48
      12: std::panicking::try::do_call
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:554:40
      13: std::panicking::try
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:518:19
      14: std::panic::catch_unwind
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panic.rs:142:14
      15: std::rt::lang_start_internal
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/rt.rs:148:20
      16: std::rt::lang_start
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/rt.rs:165:17
      17: main
      18: __libc_start_call_main
                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
      19: __libc_start_main_impl
                 at ./csu/../csu/libc-start.c:392:3
      20: _start
  thread 'main' panicked at app-agent/src/main.rs:61:9:
  ALUMET agent failed to start: Pipeline failed to build
  stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   2: alumet_agent::main::{{closure}}
             at ./rust/alumet/app-agent/src/main.rs:61:9
   3: core::result::Result<T,E>::unwrap_or_else
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1426:23
   4: alumet_agent::main
             at ./rust/alumet/app-agent/src/main.rs:56:29
   5: core::ops::function::FnOnce::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
  ```

</details>

- <details>
  <summary>RUST_BACKTRACE=full</summary>

  ```log
  Stack backtrace:
       0: <E as anyhow::context::ext::StdError>::ext_context
                 at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.82/src/context.rs:27:29
       1: anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context
                 at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.82/src/context.rs:54:31
       2: alumet::agent::Agent::start
                 at ./rust/alumet/alumet/src/agent.rs:223:24
       3: alumet_agent::main
                 at ./rust/alumet/app-agent/src/main.rs:56:29
       4: core::ops::function::FnOnce::call_once
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
       5: std::sys_common::backtrace::__rust_begin_short_backtrace
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:155:18
       6: std::rt::lang_start::{{closure}}
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/rt.rs:166:18
       7: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:284:13
       8: std::panicking::try::do_call
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:554:40
       9: std::panicking::try
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:518:19
      10: std::panic::catch_unwind
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panic.rs:142:14
      11: std::rt::lang_start_internal::{{closure}}
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/rt.rs:148:48
      12: std::panicking::try::do_call
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:554:40
      13: std::panicking::try
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:518:19
      14: std::panic::catch_unwind
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panic.rs:142:14
      15: std::rt::lang_start_internal
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/rt.rs:148:20
      16: std::rt::lang_start
                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/rt.rs:165:17
      17: main
      18: __libc_start_call_main
                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
      19: __libc_start_main_impl
                 at ./csu/../csu/libc-start.c:392:3
      20: _start
  thread 'main' panicked at app-agent/src/main.rs:61:9:
  ALUMET agent failed to start: Pipeline failed to build
  stack backtrace:
   0:     0x55cfc7938456 - std::backtrace_rs::backtrace::libunwind::trace::hd6ffdc229294c06f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55cfc7938456 - std::backtrace_rs::backtrace::trace_unsynchronized::h991f79b6e9960513
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55cfc7938456 - std::sys_common::backtrace::_print_fmt::hf4ebe716f7ccda10
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55cfc7938456 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55cfc7961870 - core::fmt::rt::Argument::fmt::he0ff0e0e188c0db5
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/rt.rs:142:9
   5:     0x55cfc7961870 - core::fmt::write::he40921d4802ce2ac
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/mod.rs:1120:17
   6:     0x55cfc7935e7f - std::io::Write::write_fmt::h5de5a4e7037c9b20
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/io/mod.rs:1846:15
   7:     0x55cfc7938234 - std::sys_common::backtrace::_print::hd8e2e3f655086663
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55cfc7938234 - std::sys_common::backtrace::print::h11c067a88e3bdb22
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55cfc7939907 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
  10:     0x55cfc7939669 - std::panicking::default_hook::h1633e272b4150cf3
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:292:9
  11:     0x55cfc7939d98 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:781:13
  12:     0x55cfc7939c72 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:659:13
  13:     0x55cfc7938956 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55cfc79399c4 - rust_begin_unwind
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
  15:     0x55cfc7176115 - core::panicking::panic_fmt::ha6effc2775a0749c
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
  16:     0x55cfc717e639 - alumet_agent::main::{{closure}}::h0332982159de8860
                               at /home/a809530/rust/alumet/app-agent/src/main.rs:61:9
  17:     0x55cfc71841bd - core::result::Result<T,E>::unwrap_or_else::hbb8842171a457662
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1426:23
  18:     0x55cfc71798f0 - alumet_agent::main::h28b34b5ac0148d69
                               at /home/a809530/rust/alumet/app-agent/src/main.rs:56:29
  19:     0x55cfc71822cb - core::ops::function::FnOnce::call_once::ha2d1414af19e123b
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
  20:     0x55cfc7188a7e - std::sys_common::backtrace::__rust_begin_short_backtrace::h239fc9106fa49e13
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:155:18
  21:     0x55cfc718d921 - std::rt::lang_start::{{closure}}::h636251dc5e2de138
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/rt.rs:166:18
  22:     0x55cfc792e901 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3f2a75cbf4c937aa
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:284:13
  23:     0x55cfc792e901 - std::panicking::try::do_call::h8b4251a3ff07cb79
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:554:40
  24:     0x55cfc792e901 - std::panicking::try::h7c5a033d33a17020
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:518:19
  25:     0x55cfc792e901 - std::panic::catch_unwind::hb11e6d2bc85d3f56
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panic.rs:142:14
  26:     0x55cfc792e901 - std::rt::lang_start_internal::{{closure}}::h0f4b130784f05f2d
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/rt.rs:148:48
  27:     0x55cfc792e901 - std::panicking::try::do_call::ha5e1e15d954bfd38
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:554:40
  28:     0x55cfc792e901 - std::panicking::try::h1ebdd47dd0e39c8c
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:518:19
  29:     0x55cfc792e901 - std::panic::catch_unwind::hbc815fbc36dbbcd0
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panic.rs:142:14
  30:     0x55cfc792e901 - std::rt::lang_start_internal::h4d236095b69a230b
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/rt.rs:148:20
  31:     0x55cfc718d8fa - std::rt::lang_start::h39e9a03fe29b74c6
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/rt.rs:165:17
  32:     0x55cfc717c3ae - main
  33:     0x7f2e3053ad90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  34:     0x7f2e3053ae40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  35:     0x55cfc7176a55 - _start
  36:                0x0 - <unknown>
  ```

</details>

**Comment by TheElectronWill** [comment]
Cause: the pipeline configuration check is too strict. Pipelines that have no registered source on startup should be accepted when at least one plugin has cloned the `ControlHandle`. A precise detection could be possible by moving the capability to add new sources after the startup to another struct, but a quick and okay solution would be to simply remove the check.

Do you believe that we would need a config or CLI option to ensure that there is at least one source before startup in some use-cases?

**Comment by titouanj** [comment]
I think there should be a warning instead of a panic when no direct source is available, with a config/flag to disable it.

But if we know that not a single plugin will add a source, then it makes sense to keep the panic/error in the starting process
